### PR TITLE
Fix a small (maybe significant) error in the RO mapping

### PR DESCRIPTION
**Pull request by abbec**
The error would cause one page too much to be marked as read only.

### CODE REVIEW

**Comment by andre-richter** [comment]
Oh, important find, thank you!

Now that it got my attention, I am a bit unhappy that with the way it currently is: `__ro_end` always contains the start address of the first **non**-ro page. That is unintuitive imo.

I wonder if a better design would be to rename `__ro_start` to `__ro_first_byte`, change the `__ro_end` assignment in the linker script to to `__ro_end = . - 1;` and rename it to `__ro_last_byte`.

In the rust code, we could then calculate `ro_first_page` and `ro_last_page` by just shifting right by 12.
This would ensure that people can implicitly understand what the real bounds are, and don't need to read the code to understand that `__ro_end` is actually already outside of the RO aperture.

What do you think?

**Comment by abbec** [comment]
Yeah, I like the idea to calculate `ro_first_page_index` and `ro_last_page_index` but you could also keep the linker script labels and just have `ro_last_page_index` be subtracted by one together with a descriptive comment?

**Comment by andre-richter** [comment]
Hmm, agreed. We use the same schema for `bss` already, which we then feed to a third-party library-function that we can't and shouldn't change, so let's stay consistent there. I sketched it out as follows:

```rust
    // Finally, fill the single LVL3 table (4KiB granule). Differentiate between
    // code+RO and RW pages.
    //
    // Using the linker script, we ensure that the RO area is consecutive and
    // 4KiB aligned, and we export the boundaries via symbols.
    extern "C" {
        // The inclusive start of the read-only area, aka the address of the
        // first byte of the area.
        static mut __ro_start: u64;

        // The non-inclusive end of the read-only area, aka the address of the
        // first byte _after_ the RO area.
        static mut __ro_end: u64;
    }

    const PAGESIZE: u64 = 4096;
    let ro_first_page_index: u64 = &__ro_start as *const _ as u64 / PAGESIZE;

    // Notice the subtraction to calculate the last page index of the RO area
    // and not the first page index after the RO area.
    let ro_last_page_index: u64 = (&__ro_end as *const _ as u64 / PAGESIZE) - 1;

    let common = STAGE1_DESCRIPTOR::VALID::True
        + STAGE1_DESCRIPTOR::TYPE::Table
        + STAGE1_DESCRIPTOR::AttrIndx.val(mair::NORMAL)
        + STAGE1_DESCRIPTOR::SH::InnerShareable
        + STAGE1_DESCRIPTOR::AF::True;

    for (i, entry) in SINGLE_LVL3_TABLE.iter_mut().enumerate() {
        let j: u64 = i as u64;

        let mem_attr = if j < ro_first_page_index || j > ro_last_page_index {
```

Would you be okay to adapt your PR? If so, could you do it for the cache tutorial as well? It contains the same code again.

**Comment by abbec** [comment]
Sure, I will see if I get to it today :)

**Comment by abbec** [comment]
Fixed it up, sorry for the bad default Github UI branch name. Thanks for great tutorials and Merry Christmas!

**Comment by andre-richter** [comment]
Thanks a lot! Happy holidays to you too!

**Pull request merged**
